<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     *
     * The first twelve records are the curated destinations from the Cebu
     * reference (kawasan-falls, whale sharks, sardine run, etc.). Their
     * descriptive categories have been mapped onto the app's canonical
     * category values so filters and card tones line up.
     */
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Kawasan Falls',
                'description' => 'A three-stage cascade of turquoise water fed by mountain springs, popular for swimming and canyoneering.',
                'category' => 'Waterfall',
                'region' => 'South Cebu',
                'municipality' => 'Badian',
                'latitude' => 9.8019444,
                'longitude' => 123.3738889,
                'estimated_cost' => 500,
                'rating' => 4.7,
                'review_count' => 3200,
                'image_url' => '/images/destinations/kawasan-falls.jpg',
                'best_time_to_visit' => 'November–May (dry season)',
                'tips' => 'Go early to avoid crowds; life vests are required and rentable on-site.',
            ],
            [
                'name' => 'Oslob Whale Sharks (Tan-awan)',
                'description' => 'Guided snorkeling/boat encounter with whale sharks ("butanding") in shallow coastal waters.',
                'category' => 'Diving & Water Activities',
                'region' => 'South Cebu',
                'municipality' => 'Oslob',
                'latitude' => 9.4614,
                'longitude' => 123.3833,
                'estimated_cost' => 1000,
                'rating' => 4.5,
                'review_count' => 5100,
                'image_url' => '/images/destinations/oslob-whale-sharks.jpg',
                'best_time_to_visit' => 'Year-round; early morning (6–9 AM) has calmer water',
                'tips' => 'No sunscreen/lotion before entering the water; touching the sharks is prohibited.',
            ],
            [
                'name' => 'Moalboal (Sardine Run & Pescador Island)',
                'description' => 'A massive, swirling sardine shoal just off the shore, plus reef and wall diving near Pescador Island.',
                'category' => 'Diving & Water Activities',
                'region' => 'South Cebu',
                'municipality' => 'Moalboal',
                'latitude' => 9.95,
                'longitude' => 123.3833,
                'estimated_cost' => 800,
                'rating' => 4.7,
                'review_count' => 2700,
                'image_url' => '/images/destinations/moalboal.jpg',
                'best_time_to_visit' => 'Year-round; sardine run is most reliable May–October',
                'tips' => 'Fins and a snorkel are enough to see the sardines — no boat required from Panagsama Beach.',
            ],
            [
                'name' => 'Osmeña Peak',
                'description' => 'Cebu\'s highest point, known for its "mini Chocolate Hills" grassy ridges and sunrise views.',
                'category' => 'Mountains & Hiking',
                'region' => 'South Cebu',
                'municipality' => 'Dalaguete',
                'latitude' => 9.8167,
                'longitude' => 123.4667,
                'estimated_cost' => 100,
                'rating' => 4.6,
                'review_count' => 1450,
                'image_url' => '/images/destinations/osmena-peak.jpg',
                'best_time_to_visit' => 'December–May; arrive before sunrise',
                'tips' => 'Bring a jacket — it\'s noticeably cooler and windy at the summit.',
            ],
            [
                'name' => 'Temple of Leah',
                'description' => 'A Roman-inspired hilltop temple in Busay built as a tribute to a late wife, offering panoramic city views.',
                'category' => 'Historical & Cultural',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City (Busay)',
                'latitude' => 10.3667,
                'longitude' => 123.85,
                'estimated_cost' => 100,
                'rating' => 4.3,
                'review_count' => 2900,
                'image_url' => '/images/destinations/temple-of-leah.jpg',
                'best_time_to_visit' => 'Late afternoon for golden-hour photos',
                'tips' => 'Pair it with nearby Sirao Flower Garden in the same trip.',
            ],
            [
                'name' => 'Sirao Flower Garden',
                'description' => 'A hillside flower farm nicknamed "Little Amsterdam," known for its celosia and sunflower fields.',
                'category' => 'Nature & Eco-Tourism',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City (Sirao)',
                'latitude' => 10.3833,
                'longitude' => 123.85,
                'estimated_cost' => 100,
                'rating' => 4.2,
                'review_count' => 1800,
                'image_url' => '/images/destinations/sirao-flower-garden.webp',
                'best_time_to_visit' => 'Morning, before it gets crowded and hot',
                'tips' => 'Costumes/props are rentable on-site for photos.',
            ],
            [
                'name' => 'Basilica del Santo Niño',
                'description' => 'The oldest Roman Catholic church in the Philippines, housing the revered Santo Niño relic.',
                'category' => 'Religious Sites',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.2939,
                'longitude' => 123.9019,
                'estimated_cost' => 0,
                'rating' => 4.8,
                'review_count' => 8600,
                'image_url' => '/images/destinations/basilica-del-santo-nino.jpg',
                'best_time_to_visit' => 'Weekday mornings to avoid Mass-hour crowds',
                'tips' => 'Dress modestly; it\'s an active place of worship.',
            ],
            [
                'name' => 'Magellan\'s Cross',
                'description' => 'A cross planted by Ferdinand Magellan in 1521, marking the arrival of Christianity in the Philippines.',
                'category' => 'Historical & Cultural',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.2933,
                'longitude' => 123.9019,
                'estimated_cost' => 0,
                'rating' => 4.4,
                'review_count' => 4200,
                'image_url' => '/images/destinations/magellans-cross.jpg',
                'best_time_to_visit' => 'Anytime; combine with the nearby Basilica and Fort San Pedro',
                'tips' => 'Vendors nearby sell candles for votive offerings — prices are negotiable.',
            ],
            [
                'name' => 'Bantayan Island',
                'description' => 'A laid-back island known for white-sand beaches, sandbars, and sunset views.',
                'category' => 'Islands',
                'region' => 'North Cebu',
                'municipality' => 'Bantayan',
                'latitude' => 11.1667,
                'longitude' => 123.7167,
                'estimated_cost' => 2500,
                'rating' => 4.6,
                'review_count' => 2100,
                'image_url' => '/images/destinations/bantayan-island.jpg',
                'best_time_to_visit' => 'March–May for driest weather',
                'tips' => 'Book ferry tickets (from Hagnaya Port) in advance during peak season.',
            ],
            [
                'name' => 'Malapascua Island',
                'description' => 'A small island famous for thresher shark diving at Monad Shoal and quiet white-sand beaches.',
                'category' => 'Islands',
                'region' => 'North Cebu',
                'municipality' => 'Daanbantayan',
                'latitude' => 11.3167,
                'longitude' => 124.1167,
                'estimated_cost' => 3000,
                'rating' => 4.7,
                'review_count' => 1300,
                'image_url' => '/images/destinations/malapascua-island.webp',
                'best_time_to_visit' => 'November–May; thresher shark dives depart around 5 AM',
                'tips' => 'Book PADI dive shops ahead — thresher shark trips have limited slots.',
            ],
            [
                'name' => 'Camotes Islands',
                'description' => 'A group of islands known for Santiago Bay\'s white sand, Lake Danao, and hidden lagoons/caves.',
                'category' => 'Islands',
                'region' => 'North Cebu',
                'municipality' => 'Camotes (Poro/San Francisco/Pilar/Tudela)',
                'latitude' => 10.65,
                'longitude' => 124.3667,
                'estimated_cost' => 2000,
                'rating' => 4.5,
                'review_count' => 900,
                'image_url' => '/images/destinations/camotes-islands.webp',
                'best_time_to_visit' => 'December–May',
                'tips' => 'Rent a scooter — public transport between the islands\' towns is limited.',
            ],
            [
                'name' => 'Simala Shrine (Monastery of the Holy Eucharist)',
                'description' => 'A castle-like Marian shrine known for its intricate architecture and reported miracles.',
                'category' => 'Religious Sites',
                'region' => 'South Cebu',
                'municipality' => 'Sibonga',
                'latitude' => 10.0333,
                'longitude' => 123.6333,
                'estimated_cost' => 0,
                'rating' => 4.7,
                'review_count' => 3500,
                'image_url' => '/images/destinations/simala-shrine.jpg',
                'best_time_to_visit' => 'Weekday mornings; avoid Wednesdays (novena day crowds)',
                'tips' => 'Modest dress is enforced; cover-ups are sold/rented near the entrance.',
            ],
            [
                'name' => 'Fort San Pedro',
                'description' => 'A 16th-century military defense structure in the heart of Cebu City, full of Spanish colonial history.',
                'category' => 'Historical & Cultural',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.2924876,
                'longitude' => 123.9052983,
                'estimated_cost' => 50,
                'rating' => 4.5,
                'review_count' => 4800,
                'image_url' => '/images/destinations/fort-san-pedro.jpg',
                'best_time_to_visit' => 'Weekday mornings are quietest',
                'tips' => 'Combine with a stroll at the nearby Plaza Independencia.',
            ],
            [
                'name' => 'Tumalog Falls',
                'description' => 'A wide, curtain-like waterfall near Oslob fed by mountain springs, set amid lush jungle.',
                'category' => 'Waterfall',
                'region' => 'South Cebu',
                'municipality' => 'Oslob',
                'latitude' => 9.5075860,
                'longitude' => 123.4300294,
                'estimated_cost' => 100,
                'rating' => 4.6,
                'review_count' => 4100,
                'image_url' => '/images/destinations/tumalog-falls.jpg',
                'best_time_to_visit' => 'Early morning when sunlight hits the falls',
                'tips' => 'Combine with the whale shark watching trip; the road is steep, consider a motorbike.',
            ],
            [
                'name' => 'Canyoneering at Badian',
                'description' => 'Jump, swim, and rappel your way through the Badian canyon to Kawasan Falls with professional guides.',
                'category' => 'Diving & Water Activities',
                'region' => 'South Cebu',
                'municipality' => 'Badian',
                'latitude' => 9.8165298,
                'longitude' => 123.3602081,
                'estimated_cost' => 2500,
                'rating' => 4.9,
                'review_count' => 9800,
                'image_url' => '/images/destinations/canyoneering-at-badian.jpg',
                'best_time_to_visit' => 'December to May for clear water',
                'tips' => 'Wear secured sandals and bring a waterproof camera.',
            ],
            [
                'name' => 'Cebu Lechon (Zubuchon)',
                'description' => 'Taste Cebu\'s legendary roasted pig at Zubuchon, one of the most celebrated lechon restaurants.',
                'category' => 'Food & Restaurants',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.3210966,
                'longitude' => 123.8930912,
                'estimated_cost' => 500,
                'rating' => 4.8,
                'review_count' => 2900,
                'image_url' => '/images/destinations/cebu-lechon-zubuchon.jpg',
                'best_time_to_visit' => 'Lunch time, right when freshly roasted',
                'tips' => 'Order the crackling-lechon belly for the best experience.',
            ],
            [
                'name' => 'Carbon Market',
                'description' => 'Cebu\'s bustling public market offering local produce, dried fish, and authentic street food.',
                'category' => 'Food & Restaurants',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.2908528,
                'longitude' => 123.8964619,
                'estimated_cost' => 300,
                'rating' => 4.5,
                'review_count' => 2100,
                'image_url' => '/images/destinations/carbon-market.webp',
                'best_time_to_visit' => 'Early morning from 5am for the freshest goods',
                'tips' => 'Keep your valuables close and haggle for souvenirs.',
            ],
            [
                'name' => 'Sumilon Island',
                'description' => 'A private island resort with a shifting sandbar, clear waters, and vibrant marine life off Oslob.',
                'category' => 'Islands',
                'region' => 'South Cebu',
                'municipality' => 'Oslob',
                'latitude' => 9.3263441,
                'longitude' => 123.3833836,
                'estimated_cost' => 2000,
                'rating' => 4.6,
                'review_count' => 2800,
                'image_url' => '/images/destinations/sumilon-island.jpg',
                'best_time_to_visit' => 'Dry months of January to May',
                'tips' => 'Confirmed day-trippers pay an entrance fee; book ahead in peak season.',
            ],
            [
                'name' => 'Cebu Taoist Temple',
                'description' => 'A scenic hillside temple in Cebu City offering gardens, tiers, and panoramic city views.',
                'category' => 'Religious Sites',
                'region' => 'Metro Cebu',
                'municipality' => 'Cebu City',
                'latitude' => 10.3385498,
                'longitude' => 123.8697215,
                'estimated_cost' => 0,
                'rating' => 4.5,
                'review_count' => 3600,
                'image_url' => '/images/destinations/cebu-taoist-temple.jpg',
                'best_time_to_visit' => 'Daytime, before 5pm closing',
                'tips' => 'Walk the 81 steps and light joss sticks during Chinese holidays if open.',
            ],
            [
                'name' => 'Mactan Newtown Beach',
                'description' => 'A modern beachfront complex in Lapu-Lapu City with cafes, shops, and sunset boardwalks.',
                'category' => 'Beach',
                'region' => 'Metro Cebu',
                'municipality' => 'Lapu-Lapu City',
                'latitude' => 10.2608016,
                'longitude' => 123.9728209,
                'estimated_cost' => 500,
                'rating' => 4.4,
                'review_count' => 1800,
                'image_url' => '/images/destinations/mactan-newtown-beach.jpg',
                'best_time_to_visit' => 'Late afternoon for sunset dining',
                'tips' => 'Great spot for a relaxed evening rather than swimming.',
            ],
            [
    'name' => 'Lantaw Native Restaurant',
    'description' => 'A native-style floating restaurant built on stilts over the water in Cordova, known for grilled seafood and sunset views of Mactan.',
    'category' => 'Food & Restaurants',
    'region' => 'Metro Cebu',
    'municipality' => 'Cordova',
    'latitude' => 10.2544,
    'longitude' => 123.9581,
    'estimated_cost' => 600,
    'rating' => 4.5,
    'review_count' => 2400,
    'image_url' => '/images/destinations/lantaw.webp',
    'best_time_to_visit' => 'Sunset (around 5:30–6:30 PM) for the best views over the water',
    'tips' => 'Reserve ahead on weekends — the nipa-hut seating over the water fills up fast.',
],
[
    'name' => 'Ten Thousand Roses Cebu',
    'description' => 'A flower-filled photo garden in Cordova featuring thousands of preserved and real roses, popular for Instagram-worthy shots.',
    'category' => 'Nature & Eco-Tourism',
    'region' => 'Metro Cebu',
    'municipality' => 'Cordova',
    'latitude' => 10.2531,
    'longitude' => 123.9494,
    'estimated_cost' => 250,
    'rating' => 4.4,
    'review_count' => 1750,
    'image_url' => '/images/destinations/ten-thousand-roses.jpg',
    'best_time_to_visit' => 'Late afternoon for softer light and fewer crowds',
    'tips' => 'Weekdays are quieter for photos; some backdrop areas have separate add-on fees.',
],
[
    'name' => "Entoy's Bakasihan",
    'description' => 'A well-known seafood restaurant in Cordova serving fresh catch grilled or cooked to order, right along the coast.',
    'category' => 'Food & Restaurants',
    'region' => 'Metro Cebu',
    'municipality' => 'Cordova',
    'latitude' => 10.2478,
    'longitude' => 123.9622,
    'estimated_cost' => 500,
    'rating' => 4.4,
    'review_count' => 890,
    'image_url' => '/images/destinations/entoys-bakasihan.jpg',
    'best_time_to_visit' => 'Lunch or early dinner for the freshest seafood selection',
    'tips' => 'Ask staff to recommend the day\'s freshest catch before ordering.',
],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(
                ['name' => $destination['name']],
                $destination,
            );
        }
    }
}
